"""Embedding providers for Tony memory."""

from __future__ import annotations

from tony.memory.protocols import EmbeddingProvider
from tony.providers.ollama import OllamaProvider


class OllamaEmbeddingProvider(EmbeddingProvider):
    """Adapts the Ollama provider to Tony's embedding protocol."""

    def __init__(self, provider: OllamaProvider) -> None:
        """Create an Ollama-backed embedding provider."""
        self._provider = provider

    def embed(self, text: str) -> list[float]:
        """Return an embedding generated by Ollama."""
        return self._provider.embed(text)
